# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'course_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CourseWindow(object):
    def setupUi(self, CourseWindow):
        CourseWindow.setObjectName("CourseWindow")
        CourseWindow.resize(767, 834)
        self.centralwidget = QtWidgets.QWidget(CourseWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(0, 0, 1141, 781))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1139, 779))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.widget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1141, 781))
        self.widget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget.setObjectName("widget")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(0, 20, 461, 141))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("assets/woodle_logo.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setGeometry(QtCore.QRect(0, 170, 541, 51))
        self.lineEdit.setStyleSheet("font: 18pt \".AppleSystemUIFont\";")
        self.lineEdit.setObjectName("lineEdit")
        self.tableWidget = QtWidgets.QTableWidget(self.widget)
        self.tableWidget.setGeometry(QtCore.QRect(0, 220, 1141, 561))
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 4, item)
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(570, 170, 161, 41))
        self.pushButton.setStyleSheet("background-color: rgb(210, 210, 210);\n"
"border-radius:20px;")
        self.pushButton.setObjectName("pushButton")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        CourseWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(CourseWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 767, 24))
        self.menubar.setObjectName("menubar")
        CourseWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(CourseWindow)
        self.statusbar.setObjectName("statusbar")
        CourseWindow.setStatusBar(self.statusbar)

        self.retranslateUi(CourseWindow)
        QtCore.QMetaObject.connectSlotsByName(CourseWindow)

    def retranslateUi(self, CourseWindow):
        _translate = QtCore.QCoreApplication.translate
        CourseWindow.setWindowTitle(_translate("CourseWindow", "MainWindow"))
        self.lineEdit.setText(_translate("CourseWindow", "My Courses"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("CourseWindow", "Classroom address"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("CourseWindow", "Course information"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("CourseWindow", "Teacher\'s message"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("CourseWindow", "Zoom link"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("CourseWindow", "Tutorial/Lecture Notes"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("CourseWindow", "MWT1"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("CourseWindow", "COMP3278 Introduction to database management systems"))
        item = self.tableWidget.item(0, 2)
        item.setText(_translate("CourseWindow", "DON\'T BE LATE"))
        item = self.tableWidget.item(0, 3)
        item.setText(_translate("CourseWindow", "https://hku.zoom.us/j/98307568693?pwd=QmlqZERWeDdWRVZ3SGdqWG51YUtndz09 "))
        item = self.tableWidget.item(0, 4)
        item.setText(_translate("CourseWindow", "https://moodle.hku.hk/mod/resource/view.php?id=3168903 "))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.pushButton.setText(_translate("CourseWindow", "Send information to mail"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CourseWindow = QtWidgets.QMainWindow()
    ui = Ui_CourseWindow()
    ui.setupUi(CourseWindow)
    CourseWindow.show()
    sys.exit(app.exec_())
