# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'timetable_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TimeWindow(object):
    def setupUi(self, TimeWindow):
        TimeWindow.setObjectName("TimeWindow")
        TimeWindow.resize(844, 827)
        self.centralwidget = QtWidgets.QWidget(TimeWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(0, 0, 841, 791))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 839, 789))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.widget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget.setGeometry(QtCore.QRect(0, 0, 841, 801))
        self.widget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget.setObjectName("widget")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(0, 20, 461, 141))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("../assets/woodle_logo.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setGeometry(QtCore.QRect(0, 180, 841, 41))
        self.lineEdit.setStyleSheet("font: 18pt \".AppleSystemUIFont\";")
        self.lineEdit.setObjectName("lineEdit")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.widget)
        self.calendarWidget.setGeometry(QtCore.QRect(0, 220, 841, 541))
        self.calendarWidget.setObjectName("calendarWidget")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        TimeWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(TimeWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 844, 24))
        self.menubar.setObjectName("menubar")
        TimeWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(TimeWindow)
        self.statusbar.setObjectName("statusbar")
        TimeWindow.setStatusBar(self.statusbar)

        self.retranslateUi(TimeWindow)
        QtCore.QMetaObject.connectSlotsByName(TimeWindow)

    def retranslateUi(self, TimeWindow):
        _translate = QtCore.QCoreApplication.translate
        TimeWindow.setWindowTitle(_translate("TimeWindow", "MainWindow"))
        self.lineEdit.setText(_translate("TimeWindow", "My Timetable"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CourseWindow = QtWidgets.QMainWindow()
    ui = Ui_CourseWindow()
    ui.setupUi(CourseWindow)
    CourseWindow.show()
    sys.exit(app.exec_())
